services:
  db:
    image: postgres:16
    container_name: cc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crise_conscience
    ports:
      - "5432:5432"
    volumes:
      - cc_pgdata:/var/lib/postgresql/data

volumes:
  cc_pgdata: